services:
  bd:
    container_name: ${MONGO_DB}
    image: mongo:6.0
    volumes:
      - poke-vol:/data/db
    # ports:
    #   - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    command: ["mongod", "--auth"]

  mongo-express:
    depends_on:
      - bd
    container_name: mongo-express
    image: mongo-express:1.0.0-alpha.4
    environment:
      ME_CONFIG_MONGODB_SERVER: ${MONGO_DB}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
    ports:
      - 8080:8081
    restart: always

  poke-app:
    depends_on:
      - bd
      - mongo-express
    container_name: poke-app
    image: klerith/pokemon-nest-app:1.0.0
    ports:
      - 3000:3000
    environment:
      DB_NAME: ${MONGO_DB}
      MONGODB: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_DB}:27017
    restart: always

volumes:
  poke-vol:
    external: false